CREATE DATABASE IF NOT EXISTS `DASSER_MISHROLE`;
USE DASSER_MISHROLE;

CREATE TABLE IF NOT EXISTS STATUS (
    ID INT AUTO_INCREMENT NOT NULL,
    NAME TEXT NOT NULL,
    CONSTRAINT `PK_STATUS` PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ROLE (
    ID INT AUTO_INCREMENT NOT NULL,
    NAME TEXT NOT NULL,
    CONSTRAINT `PK_ROLE` PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER (
    ID INT AUTO_INCREMENT NOT NULL,
    LASTNAME TEXT NOT NULL,
    FIRSTNAME TEXT NOT NULL,
    LOGIN VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    STATUS INT NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `PK_USER` PRIMARY KEY (ID),
    CONSTRAINT `USER_FK_STATUS` FOREIGN KEY (STATUS) REFERENCES STATUS(ID)
);

CREATE TABLE IF NOT EXISTS USER_HAS_ROLE (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CONSTRAINT `PK_USER_HAS_ROLE` PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT `USER_HAS_ROLE_FK_USER` FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT `USER_HAS_ROLE_FK_ROLE` FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);
